<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPR8CwjP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPR8CwjP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPR8CwjP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPR8CwjP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPR8CwjP\App_KernelDevDebugContainer([
    'container.build_hash' => 'PR8CwjP',
    'container.build_id' => '7fc20b8e',
    'container.build_time' => 1643803995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPR8CwjP');
